name: Environment Vars and Data Passing
on:
  workflow_dispatch:

env:
  GLOBAL: THIS_IS_GLOBAL_SCOPED

jobs:
  job-1:
    runs-on: ubuntu-24.04
    env:
      JOB_1: THIS_IS_JOB_1_SCOPED

    # Make foo available to other jobs
    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}

    steps:
      - name: Generate and export foo
        id: generate-foo
        run: |
          foo=bar

          # 1) Step output (for job output)
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"

          # 2) Job-scoped environment variable
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: Inspect values inside job-1
        run: |
          echo "GLOBAL (workflow-level):    $GLOBAL"
          echo "JOB_1 (job-level):          $JOB_1"
          echo "FOO (set via GITHUB_ENV):   $FOO"
          echo "foo (step output):          ${{ steps.generate-foo.outputs.foo }}"

  job-2:
    runs-on: ubuntu-24.04
    needs: job-1
    env:
      JOB_2: THIS_IS_JOB_2_SCOPED

    steps:
      - name: Inspect values inside job-2 (note FOO is unset)
        run: |
          echo "GLOBAL (workflow-level): $GLOBAL"
          echo "JOB_2 (job-level):       $JOB_2"
          echo "Value from job-1:        ${{ needs.job-1.outputs.foo }}"
          echo "FOO in job-2:            ${FOO:-<UNSET>}"

  job-staging:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      # Inject repository-level secret & variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
      # Inject environment-level items into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}

    steps:
      - name: Inspect values inside job
        run: |
          echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
          echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"

  job-production:
    runs-on: ubuntu-24.04
    environment: production
    env:
      # Inject repository-level secret & variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
      # Inject environment-level items into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}

    steps:
      - name: Inspect values inside job
        run: |
          echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
          echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"

  job-artifact-producer:
    runs-on: ubuntu-24.04
    steps:
      - name: Create artifact file
        run: |
          echo "This will be stored as an artifact!" > artifact.txt
          echo "Generated by job-artifact-producer on $(date)" >> artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: artifact.txt

  job-artifact-consumer:
    runs-on: ubuntu-24.04
    needs: job-artifact-producer
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-artifact

      - name: Cat artifact file
        run: |
          cat artifact.txt
