name: Passing Variables between Jobs
on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-24.04

    # Make foo available to other jobs
    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
      - name: Generate and export foo
        id: generate-foo
        run: |
          foo=bar

          # 1) Step output (for job output)
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"

          # 2) Job-scoped environment variable
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: Inspect values inside job-1
        run: |
          echo "FOO (set via GITHUB_ENV):   $FOO"
          echo "foo (step output):          ${{ steps.generate-foo.outputs.foo }}"

  job-2:
    runs-on: ubuntu-24.04
    needs: job-1
    steps:
      - name: Inspect values inside job-2 (note FOO is unset)
        run: |
          echo "Value from job-1:        ${{ needs.job-1.outputs.foo }}"
          echo "FOO in job-2:            ${FOO:-<UNSET>}"
