name: Trigger Events
on:
  # TODO: Add the most useful events here
  # - Push to main
  # - PR creation/synchronization
  workflow_dispatch:
jobs:
  echo-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Dump full event JSON
        run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          cat "$GITHUB_EVENT_PATH"
