name: Matrix and Conditionals

on:
  workflow_dispatch:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
        letter: [a, b, c]

    steps:
      # Step 1 – always runs: show the current combination
      - name: Echo number and letter
        run: |
          echo "Number: ${{ matrix.number }}"
          echo "Letter: ${{ matrix.letter }}"

      # Step 2 – run for every combo EXCEPT number=2 ∧ letter=c
      - name: Run everywhere except 2c
        if: ${{ ! (matrix.number == 2 && matrix.letter == 'c') }}
        run: echo "✔ This step runs for ${{ matrix.number }}${{ matrix.letter }}"
