name: Reuseable Workflow Demo

on:
  workflow_dispatch:

jobs:
  call-reuseable-workflow:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/06-authoring-actions--02-reuseable-workflows-source.yaml
        with:
          foo: bar
          EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
